-- MonEcole - Pedagogie securisee
-- Date : 2026-07-14
--
-- Objectif :
-- - Cahier de texte : seul le professeur auteur/programme peut modifier ou supprimer.
-- - Balayage : liste de service par classe, limitee a l'ecole.
-- - Sujets : evaluations, compositions et tests prepares par le professeur.
--
-- A executer dans Supabase SQL Editor apres le script RLS complet.

begin;

create or replace function public.monecole_current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select lower(coalesce(u.role, ''))
  from public.utilisateurs u
  where u.auth_id = auth.uid()
  order by u.id
  limit 1
$$;

revoke all on function public.monecole_current_user_role() from public;
grant execute on function public.monecole_current_user_role() to authenticated;

create or replace function public.monecole_is_professeur()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.monecole_current_user_role() in ('professeur', 'enseignant')
$$;

revoke all on function public.monecole_is_professeur() from public;
grant execute on function public.monecole_is_professeur() to authenticated;

create or replace function public.monecole_can_manage_pedagogie()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.monecole_current_user_role() in ('professeur', 'enseignant', 'administrateur', 'admin', 'directeur')
$$;

revoke all on function public.monecole_can_manage_pedagogie() from public;
grant execute on function public.monecole_can_manage_pedagogie() to authenticated;

create table if not exists public.cahier_textes (
  id bigint generated by default as identity primary key,
  etablissement_id bigint not null,
  classe_id text not null,
  matiere_id text,
  emploi_temps_id text,
  date_lecon date not null default current_date,
  heure_debut text,
  heure_fin text,
  contenu text not null,
  professeur_auth_id uuid not null default auth.uid(),
  created_by_auth_id uuid not null default auth.uid(),
  updated_by_auth_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.balayage_classes (
  id bigint generated by default as identity primary key,
  etablissement_id bigint not null,
  classe_id text not null,
  periode text not null,
  equipe text,
  eleves jsonb not null default '[]'::jsonb,
  notes text,
  created_by_auth_id uuid not null default auth.uid(),
  updated_by_auth_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sujets_pedagogiques (
  id bigint generated by default as identity primary key,
  etablissement_id bigint not null,
  classe_id text not null,
  matiere_id text,
  type_sujet text not null default 'Evaluation',
  titre text not null,
  contenu text not null,
  correction text,
  statut text not null default 'brouillon',
  professeur_auth_id uuid not null default auth.uid(),
  created_by_auth_id uuid not null default auth.uid(),
  updated_by_auth_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cahier_textes_ecole_classe_date_idx
  on public.cahier_textes(etablissement_id, classe_id, date_lecon desc);

create index if not exists balayage_classes_ecole_classe_idx
  on public.balayage_classes(etablissement_id, classe_id);

create index if not exists sujets_pedagogiques_ecole_prof_idx
  on public.sujets_pedagogiques(etablissement_id, professeur_auth_id, created_at desc);

grant select, insert, update, delete on public.cahier_textes to authenticated;
grant select, insert, update, delete on public.balayage_classes to authenticated;
grant select, insert, update, delete on public.sujets_pedagogiques to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.cahier_textes enable row level security;
alter table public.cahier_textes force row level security;
alter table public.balayage_classes enable row level security;
alter table public.balayage_classes force row level security;
alter table public.sujets_pedagogiques enable row level security;
alter table public.sujets_pedagogiques force row level security;

drop policy if exists monecole_cahier_select on public.cahier_textes;
drop policy if exists monecole_cahier_insert_prof on public.cahier_textes;
drop policy if exists monecole_cahier_update_prof on public.cahier_textes;
drop policy if exists monecole_cahier_delete_prof on public.cahier_textes;

create policy monecole_cahier_select on public.cahier_textes
for select to authenticated
using (public.monecole_is_current_etablissement(etablissement_id));

create policy monecole_cahier_insert_prof on public.cahier_textes
for insert to authenticated
with check (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_is_professeur()
  and professeur_auth_id = auth.uid()
  and created_by_auth_id = auth.uid()
);

create policy monecole_cahier_update_prof on public.cahier_textes
for update to authenticated
using (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_is_professeur()
  and professeur_auth_id = auth.uid()
)
with check (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_is_professeur()
  and professeur_auth_id = auth.uid()
);

create policy monecole_cahier_delete_prof on public.cahier_textes
for delete to authenticated
using (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_is_professeur()
  and professeur_auth_id = auth.uid()
);

drop policy if exists monecole_balayage_select on public.balayage_classes;
drop policy if exists monecole_balayage_insert on public.balayage_classes;
drop policy if exists monecole_balayage_update on public.balayage_classes;
drop policy if exists monecole_balayage_delete on public.balayage_classes;

create policy monecole_balayage_select on public.balayage_classes
for select to authenticated
using (public.monecole_is_current_etablissement(etablissement_id));

create policy monecole_balayage_insert on public.balayage_classes
for insert to authenticated
with check (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_can_manage_pedagogie()
  and created_by_auth_id = auth.uid()
);

create policy monecole_balayage_update on public.balayage_classes
for update to authenticated
using (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_can_manage_pedagogie()
)
with check (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_can_manage_pedagogie()
);

create policy monecole_balayage_delete on public.balayage_classes
for delete to authenticated
using (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_can_manage_pedagogie()
);

drop policy if exists monecole_sujets_select on public.sujets_pedagogiques;
drop policy if exists monecole_sujets_insert_prof on public.sujets_pedagogiques;
drop policy if exists monecole_sujets_update_prof on public.sujets_pedagogiques;
drop policy if exists monecole_sujets_delete_prof on public.sujets_pedagogiques;

create policy monecole_sujets_select on public.sujets_pedagogiques
for select to authenticated
using (public.monecole_is_current_etablissement(etablissement_id));

create policy monecole_sujets_insert_prof on public.sujets_pedagogiques
for insert to authenticated
with check (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_is_professeur()
  and professeur_auth_id = auth.uid()
  and created_by_auth_id = auth.uid()
);

create policy monecole_sujets_update_prof on public.sujets_pedagogiques
for update to authenticated
using (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_is_professeur()
  and professeur_auth_id = auth.uid()
)
with check (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_is_professeur()
  and professeur_auth_id = auth.uid()
);

create policy monecole_sujets_delete_prof on public.sujets_pedagogiques
for delete to authenticated
using (
  public.monecole_is_current_etablissement(etablissement_id)
  and public.monecole_is_professeur()
  and professeur_auth_id = auth.uid()
);

create or replace view public.monecole_pedagogie_rls_audit as
select
  n.nspname as table_schema,
  c.relname as table_name,
  c.relrowsecurity as rls_enabled,
  c.relforcerowsecurity as rls_forced,
  coalesce(p.policy_count, 0) as policy_count,
  case
    when c.relrowsecurity and c.relforcerowsecurity and coalesce(p.policy_count, 0) > 0 then 'OK'
    else 'A_VERIFIER'
  end as statut
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
left join (
  select schemaname, tablename, count(*)::int as policy_count
  from pg_policies
  group by schemaname, tablename
) p on p.schemaname = n.nspname and p.tablename = c.relname
where n.nspname = 'public'
  and c.relname in ('cahier_textes', 'balayage_classes', 'sujets_pedagogiques');

grant select on public.monecole_pedagogie_rls_audit to authenticated;

commit;

-- Verification :
-- select * from public.monecole_pedagogie_rls_audit;
